# NSE F&O permitted stocks — updated periodically
FNO_SYMBOLS = [
    "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK","HINDUNILVR","ITC","SBIN","BHARTIARTL","KOTAKBANK",
    "LT","AXISBANK","ASIANPAINT","MARUTI","SUNPHARMA","TATAMOTORS","WIPRO","ULTRACEMCO","NESTLEIND","TITAN",
    "TECHM","INDUSINDBK","POWERGRID","NTPC","ONGC","COALINDIA","BPCL","HCLTECH","BAJFINANCE","BAJAJFINSV",
    "M&M","GRASIM","ADANIPORTS","DIVISLAB","DRREDDY","CIPLA","EICHERMOT","SHREECEM","HINDZINC","VEDL",
    "ADANIENT","ADANIGREEN","ADANIPOWER","ADANITRANS","AMBUJACEM","ACC","APOLLOHOSP","AUROPHARMA","BANDHANBNK",
    "BANKBARODA","BATAINDIA","BEL","BERGEPAINT","BHARATFORGE","BHEL","BIOCON","BOSCHLTD","BRITANNIA","CANBK",
    "CHOLAFIN","COLPAL","CONCOR","CUMMINSIND","DABUR","DALBHARAT","DEEPAKNTR","DLF","ESCORTS","FEDERALBNK",
    "GAIL","GMRINFRA","GODREJCP","GODREJPROP","GRANULES","GUJGASLTD","HAL","HAVELLS","HDFCLIFE","HEROMOTOCO",
    "HINDALCO","HINDPETRO","IDFCFIRSTB","IGL","INDIGO","INDUSTOWER","IRCTC","IEX","JSWSTEEL","JUBLFOOD",
    "LICHSGFIN","LICI","LTIM","LTTS","LUPIN","MANAPPURAM","MARICO","MCDOWELL-N","MCX","MFSL","MPHASIS",
    "MRF","MUTHOOTFIN","NAM-INDIA","NATIONALUM","NAUKRI","NBCC","NCC","NMDC","OFSS","PAGEIND","PERSISTENT",
    "PETRONET","PFC","PIIND","PNB","POLYCAB","PVRINOX","RAMCOCEM","RECLTD","SAIL","SIEMENS","SRF","SRTRANSFIN",
    "STAR","SUNTVNETWORK","SUPREMEIND","TATACHEM","TATACOMM","TATACONSUM","TATAPOWER","TATASTEEL","TRENT",
    "TVSMOTOR","UBL","UJJIVAN","UPL","VOLTAS","WHIRLPOOL","ZEEL","ZOMATO","NYKAA","PAYTM","POLICYBZR",
    "DELHIVERY","CARTRADE","DEVYANI","SAPPHIRE","RBLBANK","CESC","EXIDEIND","IPCALAB","TORNTPHARM",
    "TORNTPOWER","MOTHERSON","ASHOKLEY","RAMKRISHNA","OBEROIRLTY","MINDAIND","KNRCON","PVR",
]

PRIORITY_SYMBOLS = [
    "RELIANCE","TCS","HDFCBANK","INFY","ICICIBANK","SBIN","BHARTIARTL","KOTAKBANK","LT","AXISBANK",
    "BAJFINANCE","TATAMOTORS","MARUTI","WIPRO","SUNPHARMA","HCLTECH","NTPC","POWERGRID","ONGC","ADANIPORTS",
]
